import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Roboto, Nunito } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import { ThemeProvider } from "@/components/theme-provider";
import { accentStyle, darkAccentStyleTag } from "@/lib/theming";
import { getBranding } from "@/lib/branding";
import "./globals.css";

// Runs before paint to apply the persisted (or system) theme, avoiding a
// light->dark flash. Kept as a plain string so it can't accidentally pick up
// component state.
const THEME_INIT_SCRIPT = `
(function () {
  try {
    var stored = localStorage.getItem("coworkee-theme");
    var dark = stored ? stored === "dark" : window.matchMedia("(prefers-color-scheme: dark)").matches;
    document.documentElement.classList.toggle("dark", dark);
  } catch (e) {}
})();
`;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Preset fonts — each exposed as a CSS var; the active preset's globals.css
// block points --font-sans at the right one.
const inter = Inter({ variable: "--font-inter", subsets: ["latin"] });
const nunito = Nunito({ variable: "--font-nunito", subsets: ["latin"] });
const roboto = Roboto({ variable: "--font-roboto", subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();
  const branding = await getBranding();

  return (
    <html
      lang={locale}
      data-theme-preset={branding.themePreset}
      style={accentStyle(branding.accentColor)}
      className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${nunito.variable} ${roboto.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <head>
        <script dangerouslySetInnerHTML={{ __html: THEME_INIT_SCRIPT }} />
        {/* In dark mode, override the inline light accent with a lightened,
            legible variant (a dark accent would be low-contrast otherwise). */}
        <style dangerouslySetInnerHTML={{ __html: darkAccentStyleTag(branding.accentColor) }} />
      </head>
      <body className="min-h-full flex flex-col">
        <NextIntlClientProvider messages={messages}>
          <ThemeProvider>{children}</ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
